version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-blog-api:dev
    container_name: fastapi-blog-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Override container port without editing files:
      # PORT=8081 (in .env or exported) -> binds to host port below
      PORT: "${PORT:-8000}"
      APP_ENV: "${APP_ENV:-development}"
    ports:
      # Host port is independently configurable from container PORT for convenience.
      # Example: HOST_PORT=18000 and PORT=8081 -> host:18000 -> container:8081
      - "${HOST_PORT:-8000}:${PORT:-8000}"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${PORT:-8000}/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
